version: "1.0"
name: ci
displayName: ci
stages:
- name: 构建
  displayName: 构建
  strategy: naturally
  trigger: auto
  steps:
  - step: build@gcc
    name: ""
    displayName: GCC 构建
    gccVersion: 11.1.0
    commands:
    - apt-get update
    - apt-get install -y cmake g++ pkg-config libsystemd-dev libgtest-dev
    - ""
    - rm -rf build_release
    - rm -rf build_unit_tests
    - ""
    - cmake -S . -B build_release -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17
      -DCMAKE_CXX_STANDARD_REQUIRED=ON
    - cmake --build build_release
    - ""
    - cmake -S . -B build_unit_tests -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17
      -DCMAKE_CXX_STANDARD_REQUIRED=ON
    - cmake --build build_unit_tests --target sdbusxx_unit_tests
    - ctest --test-dir build_unit_tests --rerun-failed --output-on-failure
    artifacts:
    - name: BUILD_ARTIFACT
      path:
      - ./build_release
      type: .tar.gz
    strategy:
      retry: "0"
      resource:
        cpu: "2"
        memory: "4"
- name: 部署
  displayName: 部署
  strategy: naturally
  trigger: auto
  steps:
  - step: release@gitee
    name: c1c76b0e
    displayName: Gitee Release
    releaseName: sdbusxx_master
    description: sdbusxx_master
    tagName: master_build
    upstreamArtifact:
    - BUILD_ARTIFACT
    assertFiles: []
    prerelease: false
    allowUpdate: true
    strategy:
      retry: "0"
      resource:
        cpu: "2"
        memory: "4"
triggers:
  trigger: manual
notify: []
strategy:
  blocking: true
